package com.udacity.project4.utils

const val   REQUEST_LOCATION_PERMISSION = 100
const val REQUEST_BACKGROUND_LOCATION_PERMISSION = 101
const val REQUEST_WAKE_LOCK_PERMISSION = 102
const val ACTION_GEOFENCE_EVENT = "ACTION_GEOFENCE_EVENT"